include:
  - board: nice_nano_v2
    shield: splitkb_aurora_corne_left nice_view_adapter nice_view
    extra-args: -DCONFIG_ZMK_KEYBOARD_NAME=\"Corne6x3\"
  - board: nice_nano_v2
    shield: splitkb_aurora_corne_right
    extra-args: -DCONFIG_ZMK_KEYBOARD_NAME=\"Corne6x3\"
