include:
  - board: nice_nano_v2
    shield: splitkb_aurora_corne_left nice_view_adapter nice_view
    artifact-name: aurora_corne_left
  - board: nice_nano_v2
    shield: splitkb_aurora_corne_right
    artifact-name: aurora_corne_right
