include:
  - board: nice_nano_v2
    shield: splitkb_aurora_corne_left nice_view_gem
    snippets: [ "studio_5col" ]
  - board: nice_nano_v2
    shield: splitkb_aurora_corne_right
    snippets: [ "studio_5col" ]
